### ISSUE TITLE
线上B10K修改

### ISSUE THREAD

**Issue by guonannan** [CNGB-DC/Renaissance#11]
图中 HDM 修改为 HMD。
![fb37ce38cbedf2e077b1b58201749527](https://cloud.githubusercontent.com/assets/22789662/24034245/8eef905e-0b2b-11e7-90db-2e01d9738753.png)
@nixiaoya

**Comment by nixiaoya** [comment]
这是哪个数据库的页脚信息？ @guonannan

**Comment by guonannan** [comment]
b10k项目的，templates/main/base.html @nixiaoya

**Comment by nixiaoya** [comment]
[b10k 项目](https://b10k.genomics.cn) 页脚链接错误，已修改
