### ISSUE TITLE
#b10k# species查询无反应

### ISSUE THREAD

**Issue by ghost** [CNGB-DC/Renaissance#2]
B10 [SPECIES](http://b10k.genomics.cn/species.html) 单独选择 Search flagged taxa 条件，查询 species 无反应。

**Comment by nixiaoya** [comment]
@guonannan  小楠处理下。处理完毕后，反馈回这里

**Comment by guonannan** [comment]
已修改

**Comment by guonannan** [comment]
已修改@shenwiyn
