### ISSUE TITLE
#FishT1K# Login issue  

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Renaissance#3]
@shenwiyn 可以check一下，@duwensi 之前聊到的那个登陆认证有进展么：）

> From: Edward Smith
> Date: 2016-11-03 15:50
> To: weixiaofeng@genomics.cn
> Subject: Trouble logging into fisht1k
> Hi

> I have registered an account on the fisht1k website but I am unable to log in. If I try to re-register, it says that an account already exists with those details so I know the account has been created. Please can you help.
> 
> Thanks
> 
> Ed
> 
> -- 
> Ed Smith
> Postdoctoral Researcher
> New York University - Abu Dhabi
> Email: edsmith@nyu.edu

**Comment by duwensi** [comment]
About this guy's problem, I have activate his account manually. For same problems described from users, do the same operation to solve them. 
Global account system is still under development. It may be completed in two weeks or more.
We still need to merge the existing accounts in all dbs, this will be discuss after the system done.

**Comment by vincentweiss** [comment]
Great, pls let me know when any progress about the new account system. @shenwiyn can  reply the user while I have sent you the mail :)

**Comment by ghost** [comment]
The passwd for egs102 has been reset with the reply mail to Edward Smith edsmith@nyu.edu.

**Comment by duwensi** [comment]
No. The operation is changing the field `is_active` to True, not reset the password. @shenwiyn

**Comment by duwensi** [comment]
Account with email edsmith@nyu.edu is already activeted by me. You don't need to do it again.

**Comment by ghost** [comment]
Here is the reply mail for Edward Smith（has been sent at 9:54），so keep the egs***/xxxxx should be fine.

> Hi Edward Smith,
> The user for egs**\*  has reset the password，please try it again:
> 
> User Name: egs***（hide）
> Password: xxxxx（hide）
> 
> We decide to update the login function, Reset Passwod  may be  affected. Please contact us if there are any questions.
> 
> Regards,
> Steven Shen
