### ISSUE TITLE
#各数据库 统计表#

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Renaissance#6]
我们可以做一份统计表（这个事情以前断断续续搞了几趟），避免以后经常有人问 宣传要宣传，我们直接给链接就好。统计的信息主要是各个数据中可供检索的字段的条目数（物种，样本 etc.）
@duwensi @nixiaoya @kandicelk 刘克，惠海那边的你帮忙一下，到时汇总后放在github该项目的根目录里。

![image](https://cloud.githubusercontent.com/assets/3094890/20704320/bfba597a-b659-11e6-8e5d-1edabf941bbf.png)

**Comment by kandicelk** [comment]
已上传。 @vincentweiss 
[Database search statistics20161125.xlsx](https://github.com/CNGB-DC/Renaissance/files/612766/Database.search.statistics20161125.xlsx)

**Comment by vincentweiss** [comment]
@kandicelk @duwensi Gemap,cancer..组内人相关的数据库也统计一下

**Comment by kandicelk** [comment]
已添加gemap，cancer，出生缺陷网站，别的还有吗？ @vincentweiss 
[Database search statistics20161129.xlsx](https://github.com/CNGB-DC/Renaissance/files/618411/Database.search.statistics20161129.xlsx)

**Comment by vincentweiss** [comment]
辛苦刘克，后期每季度统计一次便可 @kandicelk
