### ISSUE TITLE
OneKP 域名 

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Renaissance#7]
年后bioinfodata的域名应该就过期了， 在此之前需要做三件事：

1. 将现有的bioinfodata域名网站 访问时转发到db.cngb.org/dbname ，并且在跳转是有一个notice信息 提醒用户 我们将取消现有的 bioinfodata域名。 @nixiaoya 

处理完后 @shenwiyn 沈老师也告知onekp团队

2. 在数据库中的页面顶部也有一个alert通知信息，告知用户 我们准备迁移到新的域名下 @duwensi 

![image](https://cloud.githubusercontent.com/assets/3094890/20785466/33357e0c-b7db-11e6-9722-8c516d0be80d.png)

**Comment by ghost** [comment]
新的域名是确定为：db.cngb.org/onekp，还是：db.cngb.org/Blast4OneKP ?

**Comment by vincentweiss** [comment]
用第二个 都用小写吧

**Comment by duwensi** [comment]
@adam-chuan 把提示栏加一下：“Attention, please. We are planning to move this website from www.bioinfodata.org to db.cngb.org, and this will done before 2016-12-7. We suggest not to submit jobs from now on until our new notification. Please plan your jobs accordingly.”

**Comment by duwensi** [comment]
@adam-chuan 以此内容为准：“Attention, please. We are going to move this website from <a>www.bioinfodata.org/Blast4OneKP/</a> to <a>db.cngb.org/blast4onekp/</a> before 2016-12-7. <br/>After that, the old url will be automatically redirected to the new one until be deleted at first day of 2017.”，注意添加a标签中的href链接。

**Comment by duwensi** [comment]
提示已更新。

**Comment by nixiaoya** [comment]
暂定为 2016/12/05日（下周一）进行域名更新，到时候会同步更新其他各数据库的友链

Blast4OneKP数据库的新链接为：http://db.cngb.org/blast4onekp/

**Comment by nixiaoya** [comment]
onekp 域名迁移已经处理完毕，新链接为：http://db.cngb.org/blast4onekp/

一级页面测试无异常，包括：
* /home
* /blast
* /job
* /species
* /search
* /document

功能测试无异常，包括：
* balst 提交任务
* blast 结果页，任务结果列表
* /species页面左侧分类树和右侧联动的 table
* 物种详情页 （/species?id=***）
* /search 页，上面 input 使用关键词 ‘a' 检索，返回结果正常。下面 input 使用关键词 ’AALA-2000001' 检索，显示匹配一条数据
* /user 登陆、登出

301 永久自动重定向正常
从 https://www.bioinfodata.org/Blast4OneKP/search  -> http://db.cngb.org/blast4onekp/search

请 @shenwiyn 确定下，我们其他还有那些站点，有 onekp 的友链需要调整的？

@shenwiyn 邮件通知下 onekp 相关人员，我们已完成了域名调整。

**Comment by nixiaoya** [comment]
@duwensi  现在是否需要取消页面上部的通知信息？

**Comment by duwensi** [comment]
提示已更新。

**Comment by ghost** [comment]
已经邮件告知 onekp 团队。

**Comment by nixiaoya** [comment]
请 @shenwiyn 确定下，**我们**其他还有哪些站点，有 onekp 的友链需要调整的？

**Comment by ghost** [comment]
以下站点 footer 部分的 onekp 链接已经调整。
- http://db.cngb.org/millet/
- http://b10k.genomics.cn/
- http://db.cngb.org/1kite/
- https://www.mt10k.org/
- http://fisht1k.org/

**Comment by nixiaoya** [comment]
进入 /pyweb 目录，试试 `grep 'www.bioinfodata.org/Blast4OneKP' ./* -R -n | grep -v 'log'` 这条命令。/pyweb 是后续开发的所有项目的目录

进入 /data/python_website/Templates 目录，运行命令 `grep 'www.bioinfodata.org/Blast4OneKP' ./* -R -n`，这个目录是之前开发的项目的模板文件目录

**Comment by ghost** [comment]
/pyweb 和 /data/python_website 下所涉及的 OneKP 链接已经更新。
biomigo search 关于 OneKP 的 api 链接已经更改，请 @guonannan 处理一下后续的工作。

**Comment by guonannan** [comment]
biomigo search 关于 OneKP 的 api 已更新 @shenwiyn。

**Comment by nixiaoya** [comment]
新域名站点的提示信息还需要保留吗？

如果不用的话，就取消提示信息，顺便关掉这个 issue 吧

**Comment by ghost** [comment]
都已经更改完成了。
