### ISSUE TITLE
#数据库迁移#

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Renaissance#8]
只是 Mark 一下。

IZBox 也离挂掉不远了，@shenwiyn @zhoufeiyu @nixiaoya 杨老师带队计划好迁移的事。

@duwensi 研究员五个数据库 和惠海沟通一下 看能否明天下午部署上去， 下周二要和xuxun开会汇报

**Comment by duwensi** [comment]
开外网访问还没批下来。

**Comment by vincentweiss** [comment]
：） 我知道的，只是为了下周会议提到的时候不那么尴尬

**Comment by nixiaoya** [comment]
项目迁移是现阶段优先级最高的任务吗？ @vincentweiss

**Comment by vincentweiss** [comment]
@nixiaoya 不是的，计划开始做，元旦前弄完。主要是IZBox上也有我们的DB。 

@duwensi 研究院这个迁移优先级还是比较高的，要不领导又要开始问了 T T

**Comment by nixiaoya** [comment]
好的， 我会着手安排人员处理

**Comment by nixiaoya** [comment]
已完成迁移流程的撰写，下一步为分配工作，开始项目迁移

**Comment by nixiaoya** [comment]
线上数据库已经开始迁移，具体进度请查看文件 《项目迁移进度.md》

**Comment by nixiaoya** [comment]
目前迁移已经完成，但解析还未完成

**Comment by ghost** [comment]
cngb.org 官网右下角的 **“数据库网站”** 发现缺少了 **"千种鱼转录组数据库（ http://fisht1k.org/ ）“**。
![qq 20170110093818](https://cloud.githubusercontent.com/assets/12521320/21790688/066e01e8-d719-11e6-80e8-5e2daf442fc4.png)

**Comment by nixiaoya** [comment]
biomigo 下也没有这条信息

@adam-chuan  在开发机器（10.21）上面调整下对应的模板文件，国际化部分联系 @guonannan  处理

官网部分我发邮件给张龙处理

中文信息为：千种鱼转录组数据库
英文信息为：Fish 1K Database
链接为：http://fisht1k.org/

信息增加在 **千种昆虫数据库** 下面

**Comment by guonannan** [comment]
千种鱼转录组数据库的添加和国际化部分已完成。

在 2017年1月10日，上午10:25，Felix Yang <notifications@github.com<mailto:notifications@github.com>> 写道：


biomigo 下也没有这条信息

@adam-chuan<https://github.com/adam-chuan> 在开发机器（10.21）上面调整下对应的模板文件，国际化部分联系 @guonannan<https://github.com/guonannan> 处理

官网部分我发邮件给张龙处理

中文信息为：千种鱼转录组数据库
英文信息为：Fish 1K Database
链接为：http://fisht1k.org/

**Comment by guonannan** [comment]
模版文件：/pyweb/search/website/templates/main/search.html
国际化文件：/pyweb/search/website/locale/zh_CN/LC_MESSAGES/django.po
![64968e52-f024-450f-8456-187945429055](https://cloud.githubusercontent.com/assets/22789662/21792576/bf70f504-d725-11e6-9c13-06d30723d7fb.png)

**Comment by nixiaoya** [comment]
db.cngb.org/search/ 已经更新了新的内容，中英文切换正常

官网部分已经发了邮件沟通

**Comment by nixiaoya** [comment]
各数据库均迁移完毕，issue closed
